config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:show]
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "sessions/new"
  get   "/signup", to: "users#new"
  get   "/login",   to: "sessions#new"
  post  "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true

  broadcasts_to -> (recipe) { "recipes" }, inserts_by: :prepend

  def to_param
    "#{id}-#{latinize(title).parameterize}"
  end

  def latinize(string)
    string.unicode_normalize(:nfd).chars.select do |char|
      char.match(/\p{Latin}|\s/)
    end.join
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :user_id, :uniqueness => { :scope => :recipe_id,
    :message => "Nur eine Bewertung per Rezept" }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :recipes
  has_many :reviews, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string;
  # Only used for test user passwords, hence using the minimum cost parameter
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def name
    fullname = "#{first_name} #{last_name}"
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

    def not_found(exception)
      render json: { error: exception.message }, status: :not_found
    end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::BaseController
  def index
    @recipes = Recipe.all.order("created_at DESC")
    render json: @recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    render json: @recipe.to_json(
      :include => {
        :reviews => {only: [:rating, :user_id]}
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url, status: :see_other
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :destroy]

  def index
    @recipes = Recipe.all.order("created_at DESC")
  end

  def show
    @recipe = get_recipe(params[:id])
    @rating = helpers.recipe_rating @recipe
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user if current_user
    if @recipe.save
      flash[:success] = "Neues Rezept hinzugefügt"
      redirect_to recipe_path(@recipe)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @recipe = get_recipe(params[:id])
  end

  def update
    @recipe = get_recipe(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = "Rezept aktualisiert"
      redirect_to recipe_path(@recipe)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    get_recipe(params[:id]).destroy
    flash[:danger] = "Rezept gelöscht"
    redirect_to recipes_path, status: :see_other
  end

  private

  def get_recipe(recipe_id)
    Recipe.find(recipe_id)
  end

  def recipe_params
    params.require(:recipe).permit(:title, :author,
                                   :description, :photo, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:new]
  
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.new(review_params)
    @review.user = current_user if current_user
    if @review.save
      redirect_to recipe_path(@recipe)
    else
      flash.now[:alert] = "Bewertung konnte nicht abgegeben werden."
      render :new, status: :unprocessable_entity 
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :user_id, :recipe_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_back_or root_url
    else
      flash.now[:danger] = "Invalid email/password combination."
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      helpers.log_in @user
      flash[:success] = "Willkommen zum Rezeptbuch!"
      redirect_to root_url
    else
      render "new", status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  # TODO Use Rails pluralisation instead
  def pluralize_reviews_de(rating)
    if rating == 1
      "#{rating}e Bewertung"
    else
      "#{rating} Bewertungen"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_flash.html.erb
<div id="flash_alert">
  <% flash.each do |message_type, message| %>
    <div class='alert alert-<%= message_type %>'><%= message %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=<%= I18n.locale %>>
  <head>
    <title>Rezeptbuch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <%= turbo_frame_tag "flash" do %>
        <%= render "layouts/flash" %>
      <% end %>
      <%= yield %>
    </div>
    <footer class="footer fixed-bottom">
      <div class="container">
        <div class="text-center">
          <ul>
            <li><%= link_to "Impressum", "#" %></li>
            <li><%= link_to "Datenschutz", "#" %></li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/recipes/_ratings.html.erb
<div class="rating mb-3 pb-3">
  <% ratings = @recipe.reviews %>
  <div>
    <% @rating.times do %>
      <i class="bi bi-star-fill"></i>
    <% end %>
    <% if ratings.present? %>
      (<%= ((ratings.map { |r| r.rating }.sum.to_f) / ratings.length).round(1) %>)
    <% end %>
  </div>
  <div>
    <em><%= pluralize_reviews_de(ratings.length) %></em>
  </div>
  <div>
    <% if ratings.empty? %>
      <em>
      <%= link_to "Sei der erste", new_recipe_review_path(@recipe),
        style: "text-decoration: none;" %>
      </em>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<%= turbo_frame_tag recipe do %>
  <div class="recipe">
    <% if recipe.photo.attached? %>
      <%= cl_image_tag(recipe.photo.key,
      width: 40, height: 30, crop: :fill) %>
    <% else %>
      <%= image_tag("recipe_placeholder.jpg",
        width: 40, height: 30, crop: :fill) %>
    <% end %>
    <%= link_to recipe.title, recipe_path(recipe) %>
  </div>
<% end %>

app/views/recipes/_recipe_card.html.erb
<% @recipes.each do | recipe |%>
  <li>
    <div class="card-product">
      <% if recipe.photo.attached? %>
        <%= cl_image_tag(recipe.photo.key,
        width: 80, height: 60, crop: :fill) %>
      <% else %>
        <%= image_tag("recipe_placeholder",
          width: 80, height: 60, crop: :fill) %>
      <% end %>
      <div class="card-product-infos">
        <%= link_to recipe.title, recipe_path(recipe), class: "card-title" %>
      </div>
    </div>
  </li>
<% end %>

app/views/recipes/_show_photo.html.erb
<% if @recipe.photo.attached? %>
  <%= cl_image_tag(@recipe.photo.key,
  width: 400, height: 300, crop: :fill) %>
<% else %>
  <%= image_tag("recipe_placeholder.jpg",
    width: 400, height: 300, crop: :fill) %>
<% end %>

app/views/recipes/edit.html.erb
<%= link_to "Zurück", recipe_path(@recipe) %>
<h1>Rezept anpassen</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: @recipe) do |f| %>
      <%= f.label "Titel" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label "Autor" %>
      <%= f.text_field :author, class: "form-control" %>
      <%= f.label "Beschreibung" %>

      <%= f.text_area :description, size: "60x10",
        class: "form-control" %>
      <%= render "show_photo"%>
      <%= f.label "Foto ändern?" %>

      <%= f.file_field :photo, direct_upload: true,
        class: "form-control" %>

      <%= f.submit "Änderungen speichern", 
        class: "btn btn-primary" %>
    <% end %>
    <%= link_to "Abbrechen", recipe_path(@recipe), 
      class: "btn btn-secondary w-100 mb-3" %>
  </div>
</div>

<hr>
<%= link_to "Zurück", recipe_path(@recipe) %>

app/views/recipes/index.html.erb
<%= turbo_stream_from "recipes" %>
<h1>Willkommen bei Ihrem Rezeptbuch</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">

    <%= link_to "Neues Gericht hinzufügen", new_recipe_path, 
      class: "btn btn-primary mt-3" %>

    <p></p>

    <h2>Was koche ich heute?</h2>
    <%= turbo_frame_tag "recipes" do %>
      <%= render @recipes %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= link_to "Zurück", recipes_path %>
<h1>Rezept hinzufügen</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: [@user, @recipe] ) do |f| %>
      <%= render "shared/error_msgs_recipe" %>

      <%= f.label :title, "Titel" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :author, "Autor" %>
      <%= f.text_field :author, class: "form-control" %>

      <%= f.label :description, "Beschreibung" %>
      <%= f.text_area :description, size: "60x10", 
        class: "form-control" %>

      <%= f.label :photo, "Foto hochladen" %>
      <%= f.file_field :photo, direct_upload: true, 
        class: "form-control" %>

      <%= f.submit "Rezept hinzufügen", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "Abbrechen", root_path, 
      class: "btn btn-secondary w-100 mb-3" %>
  </div>
</div>

<hr>
<%= link_to "Zurück", recipes_path %>

app/views/recipes/show.html.erb
<%= link_to "Zurück", root_path %>
<h1><%= @recipe.title %></h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <p>Autor: <%= @recipe.author %></p>

    <% if @recipe.user == current_user %>
      <%= link_to "Rezept anpassen", edit_recipe_path(@recipe),
        class: "btn btn-primary mb-3" %>
    <% end %>

    <div>
      <%# render "ratings" %>
      <%# turbo_frame_tag "rating", src: new_recipe_review_path(@recipe) %>
      <%= turbo_frame_tag :reviews do %>
        <div class="d-flex justify-content-between">
          <%= render "ratings" %>
          <div>
            <%= link_to "Bewertung abgeben", new_recipe_review_path(@recipe),
              class: "btn btn-secondary  mb-3" %>
          </div>
        </div>
      <% end %>

      <h2>Beschreibung</h2>
      <p><%= @recipe.description %></p>
      <p><%= render "show_photo" %></p>
      <small><p>Erstellungsdatum: 
        <%= @recipe.created_at.strftime("%d.%m.%Y") %>
      </p></small>
      
      <% if @recipe.user == current_user %>
        <%= link_to "Rezept löschen", recipe_path(@recipe),
        data: { "turbo-method": :delete,
          turbo_confirm: "Sicher? #{@recipe.title} unwiederruflich löschen" },
          class: "btn btn-danger mb-3" %>
      <% end %>
    </div>
  </div>
</div>

<hr>
<%= link_to "Zurück", root_path %>

app/views/reviews/new.html.erb
<%= turbo_frame_tag :reviews do %>

<div class="row">
  <%= form_with(model: [@recipe, @review] ) do |f| %>

    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "Fehler") %> beim speichern dieser Bewertung:</h2>
        <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <%= link_to "Bewertung anzeigen", recipe_path(@recipe), class: "btn btn-secondary" %>
    <% else %>

    <div class="col-xs-5 col-md-6 offset-md-1 pb-3">
      <%= f.label :title, "Rezept bewerten" %>
      <%= f.select :rating, (1..5).to_a,
        label: "1 - 5", class: "form-control" %>

      <%= f.submit "Bewertung abgeben", class: "btn btn-primary" %>
      <%= link_to "Abbrechen", recipe_path(@recipe), class: "btn btn-secondary w-100" %>
      <% end %>
    </div>
  <% end %>
</div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_msgs_recipe.html.erb
<% if @recipe.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@recipe.errors.count, 'error') %>.
    </div>
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_msgs_user.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark navbar-fixed-top">
    <div class="container-fluid">
      <%= link_to "Rezeptbuch", root_path, id: "logo", class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse " aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="container d-flex justify-content-between">
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <li><%= link_to "Home", root_path, class: "nav-link active" %></li>
            </li>
            <li class="nav-item">
              <li><%= link_to "Aktuelles", "#", class: "nav-link" %></li>
            </li>
            <li class="nav-item">
              <li><%= link_to "Kategorien", "#", class: "nav-link" %></li>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><%= link_to "Profil", current_user, class: "nav-link" %></li>
              <li>
                <%= link_to "Ausloggen", logout_path, class: "nav-link",
                                      data: { "turbo-method": :delete } %>
              </li>
            <% else %>
              <li><%= link_to "Anmelden", login_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <!-- Spacing between Header and the top section -->
  <div class="spacing-header-section"></div>
</header>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: @user) do |f| %>
      <%= render "shared/error_msgs_user" %>

      <%= f.label :first_name, "Vorname" %>
      <%= f.text_field :first_name, class: "form-control" %>

      <%= f.label :last_name, "Nachname" %>
      <%= f.text_field :last_name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, "Passwort (min. 6 Zeichen)" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Bestätigen" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Anmelden", class: "btn btn-primary" %>
    <% end %>

    <p><%= link_to "Log in", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-6 offset-md-3 p-3">
    <section class="user_info overflow-hidden">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <div class="center p-3">
        <%= link_to "Rezepte anzeigen", root_path, 
          class: "btn btn-primary" %>
    </div>
    <div class="center p-3">
      <% if @user == current_user %>
        <%= link_to "Neues Gericht hinzufügen", new_recipe_path, 
          class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>